# Change these first
owner: PRAVNA-Group # Your GitHub organization or username, where this repository lives
repo: risify-upptime # The name of this repository

sites:
  - name: Risify App [PL]
    url: https://panel.risify.pl
  - name: Risify API
    url: https://api.panel.risify.pl/v1/test
  - name: Risify Documents
    url: https://documents.risify.pl
  - name: Risify Assets
    url: https://assets.risify.pl/img/risify-logo-email-19092023.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /risify-upptime
  logoUrl: https://assets.risify.pl/img/risify-logo-email-19092023.png
  name: Risify Uptime
  introTitle: "Risify uptime monitor powered by Upptime"
  introMessage: Monitor statusu infrastruktury Risify
  theme: light
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
